### ISSUE TITLE
AbstractFloat

### ISSUE THREAD

**Issue by ChrisRackauckas** [shivin9/PDEOperators.jl#1]
Why the restriction to `AbstractFloat`?

https://github.com/shivin9/PDEOperators.jl/blob/master/src/fornberg.jl#L4

Usually the coefficients are integers and rationals. Restricting them to float seems a little odd. This can just be determined from the grid step.

**Comment by ChrisRackauckas** [comment]
You'd have to make sure you "free-range" the other `T`s too.

**Comment by shivin9** [comment]
ok I'll check on that. dextorious might have had some reason for defining it that way.

**Comment by dextorious** [comment]
The only reason I had was that I was only working with floating point data and wanted an easy guarantee of type stability - the code wasn't originally written to be part of a general library. In other words, I was lazy. :)

@ChrisRackauckas is right in saying that the type can just be determined from the grid step, `AbstractFloat` is unnecessarily restrictive in this case.

**Comment by shivin9** [comment]
Fixed in https://github.com/shivin9/PDEOperators.jl/commit/f1985bc49c04b9256c730848c9438956174bde98
