### ISSUE TITLE
Appropriate scaling after taking derivatives

### ISSUE THREAD

**Issue by shivin9** [shivin9/PDEOperators.jl#14]
After applying an operator on an array, the values diminish by a constant factor depending on the `grid_step` size.
eg. 
``` julia
julia> x = collect(0 : 1/99 : π);
julia> y = sin.(x);
julia> A = LinearOperator{Float64}(2,2,312,:Neumann,:Neumann;bndry_fn=(1,-1));
julia> res = A*y
312-element Array{Float64,1}:
 -2.9697    
 -1.03058e-6
 -2.06106e-6
 -3.09133e-6
 -4.12128e-6
 -5.15082e-6
 -6.17982e-6
 -7.2082e-6 
 -8.23584e-6
 -9.26264e-6
  ⋮         
 -9.28078e-6
 -8.25399e-6
 -7.22637e-6
 -6.198e-6  
 -5.16901e-6
 -4.13948e-6
 -3.10954e-6
 -0.0302921 
 -1.0488e-6 
 -3.0       
```
This is clearly incorrect as the second derivative of `sin(x)` is `cos(x)`.

However if we do
``` julia
julia> @. res = res[2:end-1]*100000
julia> res
312-element Array{Float64,1}:
    -2.9697  
    -0.103058
    -0.206106
    -0.309133
    -0.412128
    -0.515082
    -0.617982
    -0.72082 
    -0.823584
    -0.926264
     ⋮       
    -0.928078
    -0.825399
    -0.722637
    -0.6198  
    -0.516901
    -0.413948
    -0.310954
 -3029.21    
    -0.10488 
    -3.0     
```

we get the correct result (neglecting the spurious -3029.21 and scaling the boundaries separately)

**Comment by ChrisRackauckas** [comment]
Yes. It's missing the constant. Check the notes on discretizations of the Heat Equation: that operator should have `/dx^2` in there. I think that's for the user to handle though, unless you want to add a spot for a scalar (which could be useful in other ways, like diffusion needs `D*dt/dx^2`)

**Comment by dextorious** [comment]
The `D` in the diffusion equation must be left up to the user, obviously, but insofar as we automatically generate finite difference representations of PDEs, we should scale them appropriately, in my opinion. That means dividing any approximation of an nth-order derivative by `dx^n`.
