### ISSUE TITLE
Includes in the top level

### ISSUE THREAD

**Issue by ChrisRackauckas** [shivin9/PDEOperators.jl#2]
https://github.com/shivin9/PDEOperators.jl/blob/master/src/operator.jl#L1

It's usually easier to follow code if these are all together.

**Comment by shivin9** [comment]
Yeah that might be better. Then what is the criteria of file splitting in Julia?

**Comment by ChrisRackauckas** [comment]
>Then what is the criteria of file splitting in Julia?

Whenever it makes sense 👍
