### ISSUE TITLE
`BandedMatrix` constructor

### ISSUE THREAD

**Issue by ChrisRackauckas** [shivin9/PDEOperators.jl#7]
Should extend the `BandedMatrix` constructor so that you can directly turn these operators into a banded matrix.

**Comment by shivin9** [comment]
Not `AbstractBandedMatrix`?

**Comment by ChrisRackauckas** [comment]
No, an actual banded matrix. It needs to allocate anyways to do its banded direct LU/QR, which would be the main reason to do this transform. But it only needs to allocate the bands, so it's a form of sparse matrix.

**Comment by shivin9** [comment]
Extended a BandidMatrix constructor at https://github.com/shivin9/PDEOperators.jl/commit/ae856a849bf80b155d3c3e6b2848576a6a91aecb#diff-5037c961ea4b771f06aeb50e577e19a3R85
