### ISSUE TITLE
Define indexing

### ISSUE THREAD

**Issue by ChrisRackauckas** [shivin9/PDEOperators.jl#8]
You should define `getindex` operations so that way indexing works.

**Comment by ChrisRackauckas** [comment]
Indexing should also automatically give `+` and `-`. Though you may want specific fast overloads for standard `+` and `-` operations.

**Comment by shivin9** [comment]
> Indexing should also automatically give + and -. Though you may want specific fast overloads for standard + and - operations.

Can you explain that more comprehensively? Do you mean to add operators to form a sort of composed PDE operator as in LinearMaps?

**Comment by ChrisRackauckas** [comment]
Lazy composed PDE operators is another thing that's needed, but that should be a separate issue. 

Just simple `+` and `-` vs AbstractMatrices would be nice, because then you could `L + M` for any sparse matrix directly without producing a temporary like `sparse_full(L) + M`. Setting up indexing will make this `just work`, but you can make it better by setting it up to only loop through the bands. This gives you a way to then compose these even when not every operator can be of this special form.

**Comment by shivin9** [comment]
Some indexing support has also been pushed [here](https://github.com/shivin9/PDEOperators.jl/blob/extend_bandedmatrices/src/fornberg.jl#L87).

So `L+M` will produce a new LinearOperator... but we have to careful in cases where one of the operators is not symmetric as the whole thing will then change. It will need something like https://github.com/Jutho/LinearMaps.jl/blob/master/src/composition.jl maybe.

**Comment by shivin9** [comment]
well there you go
``` julia
julia> A = LinearOperator{Float64}(2,2,8);
julia> m = ones(8,8);
julia> res = A+m
LinearMaps.LinearCombination{Float64,Tuple{PDEOperators.LinearOperator{Float64,StaticArrays.SVector{3,Float64}},LinearMaps.WrappedMap{Float64,Array{Float64,2}}},Tuple{Float64,Float64}}((PDEOperators.LinearOperator{Float64,StaticArrays.SVector{3,Float64}}(2,2,8,3,[1.0,-2.0,1.0],3,4),LinearMaps.WrappedMap{Float64,Array{Float64,2}}([1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0; … ; 1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0],true,true,true,false)),(1.0,1.0))

julia> full(res)
8×8 Array{Float64,2}:
 -1.0   2.0   1.0   1.0   1.0   1.0   1.0   1.0
  2.0  -1.0   2.0   1.0   1.0   1.0   1.0   1.0
  1.0   2.0  -1.0   2.0   1.0   1.0   1.0   1.0
  1.0   1.0   2.0  -1.0   2.0   1.0   1.0   1.0
  1.0   1.0   1.0   2.0  -1.0   2.0   1.0   1.0
  1.0   1.0   1.0   1.0   2.0  -1.0   2.0   1.0
  1.0   1.0   1.0   1.0   1.0   2.0  -1.0   2.0
  1.0   1.0   1.0   1.0   1.0   1.0   2.0  -1.0
```
This "just works" property is too good.
